<?php
/**
 * HomeSrv
 *
 *
 *
 * @author Luuray
 * @copyright Rainhan System
 * @id $Id$
 *
 * Copyright (c) 2010-2018, Rainhan System
 * Site: www.rainhan.net/?proj=HomeSrv
 */

namespace Raindrop;


class WebAPIRequest extends Request
{
	protected function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
	}

	public function getRawPost()
	{
		// TODO: Implement getRawPost() method.
	}

	public function getFile($sKey)
	{
		// TODO: Implement getFile() method.
	}

	public function getMethod()
	{
		// TODO: Implement getMethod() method.
	}


}