<?php
/**
 * Raindrop Framework for PHP
 *
 * Error Page View - HTTP/1.1 403 Forbidden(aka No Permission)
 *
 * @author Luuray
 * @copyright Rainhan System
 * @id $Id$
 *
 * Copyright (c) 2010-2017, Rainhan System
 * Site: raindrop-php.rainhan.net
 */

?>
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="pragma" content="no-cache">
	<title>Forbidden(No Permission)</title>
</head>
<body>
Forbidden
</body>
</html>
