<?php
/**
 * Raindrop Framework for PHP
 *
 * Error Page View - HTTP/1.1 500 Internal server error
 *
 * @author Luuray
 * @copyright Rainhan System
 * @id $Id$
 *
 * Copyright (c) 2010-2017, Rainhan System
 * Site: raindrop-php.rainhan.net
 */

use Raindrop\Application;

?>
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="pragma" content="no-cache">
	<title>Internal server error</title>
</head>
<body>
<i>Message:</i> <?=$ViewData->Message?><br>
<i>RequestUri:</i> <?= Application::GetRequest()->getRequestUri() ?><br>
<i>Module:</i> <?= Application::GetRequest()->getModule() == null ? 'default' : Application::GetRequest()->getModule() ?>
<br>
<i>Controller:</i> <?= Application::GetRequest()->getController() ?><br>
<i>Action:</i> <?= Application::GetRequest()->getAction() ?><br>
<?php
if (Application::IsDebugging()) {
	?>
	<i>Call Stack:</i> <?= $ViewData->CallStack ?><br>
	<p><i>Backtrace:</i></p>
	<pre><?= debug_print_backtrace() ?></pre>
	<i>Last Exception:</i><br>
	<pre><?= Application::GetLastException() ?></pre>
	<?php
}
?>
</body>
</html>