<?php
/**
 * Raindrop Framework for PHP
 *
 * Error Page View - HTTP/1.1 400 Bad Request
 *
 * @author $Author$
 * @copyright Rainhan System
 * @date $Date$
 *
 * Copyright (c) 2010-2015, Rainhan System
 * Site: raindrop-php.rainhan.net
 *
 * $Id$
 *
 * @version $Rev$
 */
use Raindrop\Application;

$View->setLayout(null);
?><!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="pragma" content="no-cache">
	<title>Bad Request</title>
</head>
<body>
Bad Request
</body>
</html>